// <auto-generated />
using ControleDeUsuario.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeUsuario.Migrations
{
    [DbContext(typeof(ControleUsuarioContext))]
    [Migration("20231001182715_Usuarios")]
    partial class Usuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleDeUsuario.Models.ControleUsuario", b =>
                {
                    b.Property<int>("pessoaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pessoaID"));

                    b.Property<string>("pessoaDataNascimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pessoaEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pessoaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pessoaTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("pessoaID");

                    b.ToTable("ControleUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
